// ===================== NAVIGATION STRUCTURE =====================
// ===================== ROLES & AUTH =====================
const ROLES = {
  super_admin:     { label:"Super Admin", level:99 },
  ceo:             { label:"CEO", level:90 },
  general_manager: { label:"General Manager", level:80 },
  head_of_store:   { label:"Head of Store", level:70 },
  hr:              { label:"HR", level:60 },
  admin_ga:        { label:"Admin GA", level:50 },
  coordinator:     { label:"Koordinator", level:10 },
};
const ADMIN_ROLES = ["super_admin","ceo","general_manager","head_of_store","hr","admin_ga"];
function canAccessAll(role){ return ADMIN_ROLES.includes(role); }

var CURRENT_USER = {
  name:"Admin GA", email:"admin.ga@johenoffice.com", role:"super_admin", avatar:"JO"
};

function getRoleLabel(role){ return ROLES[role] ? ROLES[role].label : role; }

// ===================== NAVIGATION STRUCTURE =====================
const NAV = [
  { type:"label", text:"OVERVIEW" },
  { type:"item", id:"dashboard", icon:"layout-grid", text:"Dashboard" },
  { type:"label", text:"MANAGEMENT" },
  { type:"group", id:"meeting", icon:"users", text:"Meeting", children:[
    { id:"meeting-saya", text:"Meeting Saya", coordOnly:true },
    { id:"meeting-permintaan", text:"Permintaan Meeting", adminOnly:true },
    { id:"meeting-jadwal", text:"Jadwal Meeting" },
    { id:"meeting-mom", text:"Rekap MOM", adminOnly:true },
  ]},
  { type:"group", id:"aset", icon:"box", text:"Data Aset", adminOnly:true, children:[
    { id:"aset-kendaraan", text:"Kendaraan" },
    { id:"aset-digital", text:"Digital" },
    { id:"aset-simcard", text:"SIM Card" },
    { id:"aset-kantor", text:"Peralatan Kantor" },
    { id:"aset-ruko", text:"Aset Ruko" },
  ]},
  { type:"group", id:"pembayaran", icon:"credit-card", text:"Pembayaran", adminOnly:true, children:[
    { id:"bayar-listrik", text:"Listrik" },
    { id:"bayar-internet", text:"Internet" },
    { id:"bayar-aset-digital", text:"Aset Digital" },
    { id:"bayar-ipl", text:"IPL Ruko" },
  ]},
  { type:"label", text:"ADMIN", adminOnly:true },
  { type:"group", id:"kelola", icon:"user-cog", text:"Kelola Akun", adminOnly:true, children:[
    { id:"kelola-tim", text:"Kelola Tim" },
    { id:"kelola-aset-meeting", text:"Kelola Aset Meeting" },
    { id:"kelola-ruangan", text:"Kelola Ruangan" },
    { id:"kelola-akun", text:"Kelola Akun" },
    { id:"kelola-admin", text:"Kelola Admin" },
  ]},
  { type:"label", text:"AKUN" },
  { type:"item", id:"profil", icon:"circle-user", text:"Profil Saya" },
];

// helper to find breadcrumb / titles
const PAGE_META = {
  "dashboard": { title:"Dashboard", crumb:"Overview" },
  "meeting-saya": { title:"Meeting Saya", crumb:"Meeting / Meeting Saya" },
  "meeting-permintaan": { title:"Permintaan Meeting", crumb:"Meeting / Permintaan Meeting" },
  "meeting-jadwal": { title:"Jadwal Meeting", crumb:"Meeting / Jadwal Meeting" },
  "meeting-mom": { title:"Rekap MOM", crumb:"Meeting / Rekap MOM" },
  "aset-kendaraan": { title:"Kendaraan", crumb:"Data Aset / Kendaraan" },
  "aset-digital": { title:"Digital", crumb:"Data Aset / Digital" },
  "aset-simcard": { title:"SIM Card", crumb:"Data Aset / SIM Card" },
  "aset-kantor": { title:"Peralatan Kantor", crumb:"Data Aset / Peralatan Kantor" },
  "aset-ruko": { title:"Aset Ruko", crumb:"Data Aset / Aset Ruko" },
  "bayar-listrik": { title:"Listrik", crumb:"Pembayaran / Listrik" },
  "bayar-internet": { title:"Internet", crumb:"Pembayaran / Internet" },
  "bayar-aset-digital": { title:"Aset Digital", crumb:"Pembayaran / Aset Digital" },
  "bayar-ipl": { title:"IPL Ruko", crumb:"Pembayaran / IPL Ruko" },
  "kelola-tim": { title:"Kelola Tim", crumb:"Kelola Akun / Kelola Tim" },
  "kelola-aset-meeting": { title:"Kelola Aset Meeting", crumb:"Kelola Akun / Kelola Aset Meeting" },
  "kelola-ruangan": { title:"Kelola Ruangan", crumb:"Kelola Akun / Kelola Ruangan" },
  "kelola-akun": { title:"Kelola Akun", crumb:"Kelola Akun / Kelola Akun" },
  "kelola-admin": { title:"Kelola Admin", crumb:"Kelola Akun / Kelola Admin" },
  "profil": { title:"Profil Saya", crumb:"Akun / Profil Saya" },
};

// ===================== STATUS CONFIG =====================
const STATUS_STYLE = {
  "Selesai": "success", "Disetujui":"info", "Aktif":"success", "Lunas":"success", "Tersedia":"success",
  "Menunggu":"warning", "Pending":"warning", "Jatuh Tempo":"warning", "Maintenance":"warning", "Segera Habis":"warning", "Habis":"danger",
  "Ditolak":"danger", "Nonaktif":"danger", "Terlambat":"danger", "Rusak":"danger", "Expired":"danger", "Mati":"danger", "Tidak Aktif":"danger",
  "Dipinjam":"info", "Dijadwalkan":"info", "Baik":"success", "Perlu Servis":"warning",
};

// ===================== ASSET MEETING OPTIONS =====================
const MEETING_ASSET_OPTIONS = ["TV", "Speaker", "Whiteboard", "Laptop", "Proyektor", "Microphone", "Kamera"];

// ===================== DATASETS =====================
const DATASETS = {
  "meeting-saya": {
    advanced:true,
    stats:[
      {label:"Total Meeting", value:5, icon:"layout-grid", color:"accent"},
      {label:"Menunggu", value:1, icon:"clock", color:"warning"},
      {label:"Disetujui", value:1, icon:"check", color:"success"},
      {label:"Ditolak", value:1, icon:"x", color:"danger"},
    ],
    panelTitle:"Daftar Meeting", panelSub:"Seluruh daftar meeting yang anda ajukan akan tampil disini.",
    addLabel:"Request Meeting",
    searchPlaceholder:"Cari berdasarkan judul meeting",
    tableColumns:["Judul Meeting","Tanggal","Waktu","Ruangan","Status","Aksi"],
    formFields:[
      {key:"judul", label:"Judul Meeting", type:"text", placeholder:"Masukan judul meeting", required:true},
      {key:"tanggal", label:"Tanggal Meeting", type:"date", required:true},
      {key:"lokasi", label:"Lokasi Meeting", type:"select", placeholder:"Pilih lokasi meeting", options:["Meeting Room Utama","Ruang Serbaguna"], required:true},
      {key:"jamMulai", label:"Jam Mulai", type:"time", required:true},
      {key:"jamSelesai", label:"Jam Selesai", type:"time", required:true},
      {key:"why", label:"Why — Kenapa meeting ini diadakan?", type:"text", placeholder:"Jelaskan alasan dan urgensi meeting ini", required:true},
      {key:"what", label:"What — Apa yang akan dibahas?", type:"text", placeholder:"Sebutkan poin-poin yang akan dibahas", required:true},
      {key:"how", label:"How — Bagaimana hasil yang diharapkan?", type:"text", placeholder:"Jelaskan output atau keputusan yang diharapkan", required:true},
      {key:"lampiran", label:"Lampiran File (opsional)", type:"file", helper:"Format: PDF, DOC, DOCX. Maks 10MB."},
      {key:"asset", label:"Kebutuhan Asset (opsional)", type:"checkbox", options: MEETING_ASSET_OPTIONS},
    ],
    formLayout:[ ["judul"], ["tanggal","lokasi"], ["jamMulai","jamSelesai"], ["why"], ["what"], ["how"], ["lampiran"], ["asset"] ],
    records:[
      { id:1, judul:"Meeting Tim IT", tanggal:"2026-06-18", lokasi:"Ruang Serbaguna", jamMulai:"13:30", jamSelesai:"14:00", why:"Server utama perlu segera dimigrasi karena infrastruktur lama sudah tidak stabil dan sering downtime.", what:"Rencana migrasi server, timeline pelaksanaan, backup data, dan komunikasi ke seluruh tim.", how:"Dihasilkan jadwal migrasi yang jelas dengan risiko minimal dan backup penuh sebelum eksekusi.", lampiran:"notulen-tim-it.pdf", asset:["Proyektor","Whiteboard"], status:"Selesai", mom:{ ringkasan:"Tim IT membahas rencana migrasi server utama ke infrastruktur baru guna meningkatkan stabilitas sistem.", keputusan:"Migrasi server akan dilakukan minggu depan dengan downtime maksimal 2 jam pada malam hari.", actionPlan:"Siapkan backup penuh, jadwalkan downtime, dan kirim pengumuman ke seluruh tim H-2 sebelum migrasi.", pic:"Dimas Pratama", file:"notulen-tim-it.pdf" } },
      { id:2, judul:"Sinkronisasi Tim Produk", tanggal:"2026-06-20", lokasi:"Meeting Room Utama", jamMulai:"09:00", jamSelesai:"10:00", why:"Perlu sinkronisasi antar tim produk untuk menyelaraskan prioritas kerja minggu ini.", what:"Progress tugas masing-masing anggota, hambatan yang dihadapi, dan target mingguan.", how:"Semua anggota tim memiliki pemahaman yang sama tentang prioritas dan target minggu ini.", lampiran:null, asset:["Laptop","TV"], status:"Disetujui", mom:null },
      { id:3, judul:"Rapat Tim IT", tanggal:"2026-06-13", lokasi:"Meeting Room Utama", jamMulai:"11:00", jamSelesai:"11:30", why:"Update perkembangan project dan pembagian tugas baru untuk anggota tim IT.", what:"Progress project yang sedang berjalan, kendala teknis, dan penugasan task baru.", how:"Setiap anggota mendapat tugas yang jelas dan target penyelesaian yang disepakati.", lampiran:null, asset:[], status:"Menunggu", mom:null },
      { id:4, judul:"Review Kontrak Sewa", tanggal:"2026-06-08", lokasi:"Meeting Room Utama", jamMulai:"10:10", jamSelesai:"11:00", why:"Kontrak sewa akan berakhir dan perlu review sebelum perpanjangan atau relokasi.", what:"Klausul kontrak, kenaikan biaya sewa, opsi relokasi, dan rekomendasi tim legal.", how:"Diperoleh keputusan terbaik mengenai perpanjangan atau relokasi sesuai hasil review.", lampiran:"draft-kontrak.docx", asset:["Microphone"], status:"Ditolak", mom:null },
      { id:5, judul:"Perancangan Sistem Web", tanggal:"2026-05-28", lokasi:"Ruang Serbaguna", jamMulai:"14:23", jamSelesai:"15:10", why:"Perlu finalisasi wireframe dan pembagian tugas untuk mempercepat menuju rilis MVP.", what:"Progres wireframe, tecnologia stack, timeline pengembangan, dan alokasi resource.", how:"Wireframe final disepakati dan timeline pengembangan MVP ditetapkan dengan task assignment yang jelas.", lampiran:null, asset:["Proyektor","Speaker"], status:"Selesai", mom:{ ringkasan:"Diskusi mengenai progres wireframe sistem web dan kesiapan tim menuju rilis MVP.", keputusan:"Wireframe final disepakati dan target rilis MVP ditetapkan akhir Juli 2026.", actionPlan:"Tim desain menyelesaikan high-fidelity mockup, tim dev mulai setup environment development minggu ini.", pic:"Sari Wulandari", file:null } },
    ],
  },
  "meeting-permintaan": {
    stats:[
      {label:"Total Permintaan", value:8, icon:"inbox", color:"accent"},
      {label:"Menunggu Review", value:3, icon:"clock", color:"warning"},
      {label:"Disetujui", value:4, icon:"check", color:"success"},
      {label:"Ditolak", value:1, icon:"x", color:"danger"},
    ],
    panelTitle:"Permintaan Meeting", panelSub:"Tinjau dan kelola permintaan meeting dari seluruh tim.",
    hideAddButton:true,
    searchPlaceholder:"Cari berdasarkan nama pemohon",
    columns:["Pemohon","Judul Meeting","Tanggal","Ruangan","Status","Aksi"],
    rows:[
      {cols:["Dimas Pratama","Evaluasi Vendor IT","20 Jun 2026","Meeting Room Utama"], status:"Menunggu", why:"Perlu evaluasi kinerja vendor IT saat ini sebelum kontrak diperpanjang.", what:"Membahas performa layanan, SLA, dan biaya vendor IT selama 6 bulan terakhir.", how:"Diharapkan diperoleh keputusan perpanjangan kontrak atau tender ulang."},
      {cols:["Sari Wulandari","Sosialisasi SOP Baru","21 Jun 2026","Ruang Serbaguna"], status:"Menunggu", why:"SOP baru perlu disosialisasikan ke seluruh tim agar penerapan berjalan seragam.", what:"Memaparkan isi SOP baru, alur kerja, dan perubahan prosedur dari SOP lama.", how:"Diharapkan seluruh tim memahami dan siap menerapkan SOP baru sesuai jadwal."},
      {cols:["Andi Saputra","Rapat Anggaran Q3","22 Jun 2026","Meeting Room Utama"], status:"Disetujui", why:"Perlunya penyesuaian anggaran Q3 berdasarkan realisasi Q2.", what:"Review realisasi anggaran Q2 dan pembahasan alokasi anggaran Q3 per divisi.", how:"Dihasilkan rancangan anggaran Q3 yang matang untuk diajukan ke CEO."},
      {cols:["Rina Marlina","Onboarding Karyawan","19 Jun 2026","Ruang Serbaguna"], status:"Disetujui", why:"Ada 3 karyawan baru yang perlu menjalani sesi onboarding.", what:"Pengenalan visi misi perusahaan, struktur organisasi, dan budaya kerja.", how:"Karyawan baru dapat beradaptasi dengan cepat dan memahami perannya."},
      {cols:["Fajar Nugroho","Review Kontrak Sewa","17 Jun 2026","Meeting Room Utama"], status:"Ditolak", why:"Kontrak sewa ruko akan berakhir dan perlu review sebelum perpanjangan.", what:"Membahas klausul kontrak, kenaikan harga sewa, dan opsi relokasi.", how:"Diharapkan ada keputusan perpanjangan atau opsi relokasi terbaik."},
    ],
  },
  "meeting-jadwal": {
    advanced:true,
    stats:[
      {label:"Jadwal Hari Ini", value:2, icon:"calendar-days", color:"accent"},
      {label:"Minggu Ini", value:9, icon:"calendar", color:"info"},
      {label:"Ruangan Dipakai", value:3, icon:"door-open", color:"warning"},
      {label:"Ruangan Kosong", value:2, icon:"door-closed", color:"success"},
    ],
    panelTitle:"Jadwal Meeting", panelSub:"Lihat seluruh jadwal meeting yang sudah terkonfirmasi.",
    addLabel:"+ Tambah Jadwal",
    searchPlaceholder:"Cari...",
    tableColumns:["Judul Meeting","Tanggal","Waktu","Ruangan","Status","Aksi"],
    formFields:[
      {key:"judul", label:"Judul Meeting", type:"text", placeholder:"Masukan judul meeting", required:true},
      {key:"tanggal", label:"Tanggal Meeting", type:"date", required:true},
      {key:"lokasi", label:"Ruangan", type:"select", placeholder:"Pilih ruangan", options:["Meeting Room Utama","Ruang Serbaguna","Ruang Diskusi A","Ruang Diskusi B","Ruang Direksi"], required:true},
      {key:"jamMulai", label:"Jam Mulai", type:"time", required:true},
      {key:"jamSelesai", label:"Jam Selesai", type:"time", required:true},
    ],
    formLayout:[ ["judul"], ["tanggal","lokasi"], ["jamMulai","jamSelesai"] ],
    records:[
      { id:1, judul:"Sinkronisasi Tim Produk", tanggal:"2026-06-20", jamMulai:"09:00", jamSelesai:"10:00", lokasi:"Meeting Room Utama", status:"Dijadwalkan" },
      { id:2, judul:"Review Desain UI", tanggal:"2026-06-20", jamMulai:"13:00", jamSelesai:"14:00", lokasi:"Ruang Serbaguna", status:"Dijadwalkan" },
      { id:3, judul:"Rapat Bulanan GA", tanggal:"2026-06-23", jamMulai:"10:00", jamSelesai:"11:30", lokasi:"Meeting Room Utama", status:"Dijadwalkan" },
      { id:4, judul:"Interview Kandidat Finance", tanggal:"2026-06-24", jamMulai:"15:00", jamSelesai:"16:00", lokasi:"Ruang Serbaguna", status:"Dijadwalkan" },
      { id:5, judul:"Daily Standup Tim IT", tanggal:"2026-06-15", jamMulai:"09:00", jamSelesai:"09:30", lokasi:"Meeting Room Utama", status:"Selesai" },
      { id:6, judul:"Brainstorming Produk Baru", tanggal:"2026-06-22", jamMulai:"14:00", jamSelesai:"16:00", lokasi:"Ruang Serbaguna", status:"Dijadwalkan" },
      { id:7, judul:"Evaluasi Kinerja Q2", tanggal:"2026-06-25", jamMulai:"10:00", jamSelesai:"12:00", lokasi:"Meeting Room Utama", status:"Dijadwalkan" },
      { id:8, judul:"Meeting dengan Vendor", tanggal:"2026-06-18", jamMulai:"11:00", jamSelesai:"12:00", lokasi:"Ruang Serbaguna", status:"Disetujui" },
      { id:9, judul:"Weekly Sync Tim Marketing", tanggal:"2026-06-19", jamMulai:"15:30", jamSelesai:"16:00", lokasi:"Meeting Room Utama", status:"Selesai" },
    ],
    weeklyRecurring:[
      { judul:"Daily Standup", hari:"Senin\u2013Jumat", jam:"09:00\u201309:30", ruangan:"Meeting Room Utama" },
      { judul:"Weekly Sync Marketing", hari:"Jumat", jam:"15:30\u201316:00", ruangan:"Meeting Room Utama" },
      { judul:"Sprint Planning", hari:"Senin (2 mingguan)", jam:"10:00\u201311:30", ruangan:"Ruang Serbaguna" },
    ],
    legendItems:[
      { label:"Dipesan / Dijadwalkan", color:"info" },
      { label:"Disetujui / Berlangsung", color:"success" },
      { label:"Menunggu / Antrian", color:"warning" },
      { label:"Selesai", color:"accent" },
    ],
  },
  "meeting-mom": {
    stats:[
      {label:"Total MOM", value:14, icon:"file-text", color:"accent"},
      {label:"Bulan Ini", value:5, icon:"calendar", color:"info"},
      {label:"Sudah Direview", value:11, icon:"check-check", color:"success"},
      {label:"Belum Direview", value:3, icon:"clock", color:"warning"},
    ],
    panelTitle:"Rekap Minutes of Meeting", panelSub:"Dokumentasi hasil setiap meeting yang telah dilaksanakan.",
    hideAddButton:true,
    records:[
      { id:1, judul:"Meeting Tim IT", pic:"Dimas Pratama", dibuat_oleh:"Dimas Pratama", tanggal_meeting:"18 Jun 2026", dikirim:"20 Jun 2026", file:"notulen-tim-it.pdf", status:"Selesai",
        why:"Server utama perlu segera dimigrasi karena infrastruktur lama sudah tidak stabil.",
        what:"Rencana migrasi server, timeline, backup data, dan komunikasi ke seluruh tim.",
        how:"Dihasilkan jadwal migrasi yang jelas dengan risiko minimal dan backup penuh.",
        mom:{ ringkasan:"Tim IT membahas rencana migrasi server utama ke infrastruktur baru guna meningkatkan stabilitas sistem.", keputusan:"Migrasi server akan dilakukan minggu depan dengan downtime maksimal 2 jam pada malam hari.", actionPlan:"Siapkan backup penuh, jadwalkan downtime, dan kirim pengumuman ke seluruh tim H-2 sebelum migrasi.", pic:"Dimas Pratama", file:"notulen-tim-it.pdf" } },
      { id:2, judul:"Rapat Anggaran Q3", pic:"Andi Saputra", dibuat_oleh:"Andi Saputra", tanggal_meeting:"15 Jun 2026", dikirim:"16 Jun 2026", file:null, status:"Selesai",
        why:"Perlunya penyesuaian anggaran Q3 berdasarkan realisasi Q2.",
        what:"Review realisasi anggaran Q2 dan pembahasan alokasi anggaran Q3 per divisi.",
        how:"Dihasilkan rancangan anggaran Q3 yang matang untuk diajukan ke CEO.",
        mom:{ ringkasan:"Review realisasi anggaran Q2 dan pembahasan alokasi Q3 per divisi.", keputusan:"Anggaran Q3 disetujui dengan beberapa penyesuaian pada divisi Marketing.", actionPlan:"Finance menyusun ulang detail anggaran dan submit ke CEO paling lambat akhir bulan.", pic:"Andi Saputra", file:null } },
      { id:3, judul:"Onboarding Karyawan", pic:"Rina Marlina", dibuat_oleh:"Rina Marlina", tanggal_meeting:"12 Jun 2026", dikirim:"13 Jun 2026", file:"modul-onboarding.pdf", status:"Menunggu",
        why:"Ada 3 karyawan baru yang perlu menjalani sesi onboarding.",
        what:"Pengenalan visi misi perusahaan, struktur organisasi, dan budaya kerja.",
        how:"Karyawan baru dapat beradaptasi dengan cepat dan memahami perannya.",
        mom:{ ringkasan:"Sesi onboarding untuk 3 karyawan baru dari divisi berbeda.", keputusan:"Karyawan baru akan menjalani masa probation 3 bulan dengan mentor masing-masing.", actionPlan:"HR menyiapkan jadwal mentoring dan mengirimkan modul onboarding ke masing-masing karyawan.", pic:"Rina Marlina", file:"modul-onboarding.pdf" } },
      { id:4, judul:"Perancangan Sistem Web", pic:"Sari Wulandari", dibuat_oleh:"Sari Wulandari", tanggal_meeting:"28 May 2026", dikirim:"30 May 2026", file:null, status:"Selesai",
        why:"Perlu finalisasi wireframe dan pembagian tugas untuk mempercepat menuju rilis MVP.",
        what:"Progres wireframe, tech stack, timeline pengembangan, dan alokasi resource.",
        how:"Wireframe final disepakati dan timeline pengembangan MVP ditetapkan.",
        mom:{ ringkasan:"Diskusi mengenai progres wireframe sistem web dan kesiapan tim menuju rilis MVP.", keputusan:"Wireframe final disepakati dan target rilis MVP ditetapkan akhir Juli 2026.", actionPlan:"Tim desain menyelesaikan high-fidelity mockup, tim dev mulai setup environment development minggu ini.", pic:"Sari Wulandari", file:null } },
    ],
  },

  "aset-kendaraan": {
    advanced:true,
    stats:[
      {label:"Total Kendaraan", value:5, icon:"car", color:"accent"},
      {label:"Pajak Aktif", value:3, icon:"check-circle", color:"success"},
      {label:"Pajak Mati", value:2, icon:"x-circle", color:"danger"},
    ],
    panelTitle:"Data Kendaraan", panelSub:"Seluruh aset kendaraan milik perusahaan.",
    addLabel:"+ Tambah Kendaraan",
    searchPlaceholder:"Cari berdasarkan nama kendaraan atau plat nomor",
    searchFields:["nama_kendaraan","plat"],
    tableColumns:["Nama Kendaraan","Plat Nomor","Pajak Tahunan","PIC","Status","Aksi"],
    formFields:[
      {key:"nama_kendaraan", label:"Nama Kendaraan", type:"text", placeholder:"Masukan nama kendaraan", required:true},
      {key:"jenis", label:"Jenis Kendaraan", type:"text", placeholder:"Masukan jenis kendaraan", required:true},
      {key:"plat", label:"Plat Nomor", type:"text", placeholder:"Masukan plat nomor", required:true},
      {key:"tahun", label:"Tahun", type:"text", placeholder:"Masukan tahun kendaraan", required:true},
      {key:"pajak_tahunan", label:"Pajak Tahunan (Habis)", type:"date", required:true},
      {key:"pajak_5_tahun", label:"Pajak 5 Tahun (Habis)", type:"date", required:true},
      {key:"kepemilikan", label:"Kepemilikan Status", type:"select", options:["Milik Perusahaan","Milik Pribadi","Sewa"], required:true},
      {key:"biaya", label:"Biaya Kendaraan", type:"text", placeholder:"Masukan biaya kendaraan", required:true},
      {key:"pic", label:"PIC", type:"text", placeholder:"Masukan nama PIC", required:true},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Masukan jabatan", required:true},
      {key:"keperluan", label:"Keperluan", type:"text", placeholder:"Masukan keperluan", required:true},
    ],
    formLayout:[ ["nama_kendaraan","jenis"], ["plat","tahun"], ["pajak_tahunan","pajak_5_tahun"], ["kepemilikan","biaya"], ["pic","jabatan"], ["keperluan"] ],
    tableFieldKeys:["nama_kendaraan","plat","pajak_tahunan","pic"],
    statusLabels:{ "Aktif":"Pajak Aktif", "Segera Habis":"Pajak Segera Habis", "Mati":"Pajak Mati" },
    tableFieldFormatters:{ pajak_tahunan: v => v && v.includes("-") ? formatDateID(v) : v },
    records:[
      { id:1, nama_kendaraan:"Toyota Avanza", jenis:"MPV", plat:"B 1234 JO", tahun:"2022", pajak_tahunan:"2026-12-12", pajak_5_tahun:"2027-06-15", kepemilikan:"Milik Perusahaan", biaya:"Rp 200.000.000", pic:"Dimas Pratama", jabatan:"IT Staff", keperluan:"Operasional Kantor", status:"Aktif" },
      { id:2, nama_kendaraan:"Honda Beat", jenis:"Motor", plat:"B 5678 JO", tahun:"2023", pajak_tahunan:"2026-08-04", pajak_5_tahun:"2028-08-04", kepemilikan:"Milik Perusahaan", biaya:"Rp 25.000.000", pic:"Sari Wulandari", jabatan:"Marketing Lead", keperluan:"Survey Lokasi", status:"Aktif" },
      { id:3, nama_kendaraan:"Mitsubishi L300", jenis:"Pickup", plat:"B 9012 JO", tahun:"2021", pajak_tahunan:"2026-07-01", pajak_5_tahun:"2026-07-01", kepemilikan:"Milik Perusahaan", biaya:"Rp 160.000.000", pic:"Pool Kendaraan", jabatan:"-", keperluan:"Logistik", status:"Segera Habis" },
      { id:4, nama_kendaraan:"Toyota Hiace", jenis:"Minibus", plat:"B 3456 JO", tahun:"2022", pajak_tahunan:"2026-10-30", pajak_5_tahun:"2027-10-30", kepemilikan:"Milik Perusahaan", biaya:"Rp 350.000.000", pic:"Andi Saputra", jabatan:"Finance Staff", keperluan:"Penjemputan Tamu", status:"Aktif" },
      { id:5, nama_kendaraan:"Honda Vario", jenis:"Motor", plat:"B 7890 JO", tahun:"2019", pajak_tahunan:"2026-01-02", pajak_5_tahun:"2025-01-02", kepemilikan:"Sewa", biaya:"Rp 18.000.000", pic:"-", jabatan:"-", keperluan:"Cadangan", status:"Mati" },
    ],
  },
  "aset-digital": {
    advanced:true,
    stats:[
      {label:"Total Aset Digital", value:5, icon:"laptop", color:"accent"},
      {label:"Aset Aktif", value:3, icon:"check-circle", color:"success"},
      {label:"Aset Tidak Aktif", value:2, icon:"x-circle", color:"danger"},
    ],
    panelTitle:"Data Aset Digital", panelSub:"Lisensi software, akun, dan layanan digital perusahaan.",
    addLabel:"+ Tambah Aset Digital",
    searchPlaceholder:"Cari berdasarkan nama aset",
    searchFields:["nama_aset","pic"],
    tableColumns:["Nama Aset","PIC","Jabatan","Status","Aksi"],
    formFields:[
      {key:"nama_aset", label:"Nama Aset", type:"text", placeholder:"Masukan nama aset", required:true},
      {key:"email", label:"Email", type:"text", placeholder:"Masukan email", required:true},
      {key:"mulai", label:"Mulai", type:"date", required:true},
      {key:"berakhir", label:"Berakhir", type:"date", required:true},
      {key:"biaya", label:"Biaya", type:"text", placeholder:"Masukan biaya", required:true},
      {key:"pic", label:"PIC", type:"text", placeholder:"Masukan nama PIC", required:true},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Masukan jabatan", required:true},
      {key:"keperluan", label:"Keperluan", type:"text", placeholder:"Masukan keperluan", required:true},
      {key:"status", label:"Status", type:"select", options:["Aktif","Tidak Aktif"], required:true},
    ],
    formLayout:[ ["nama_aset","email"], ["mulai","berakhir"], ["biaya"], ["pic","jabatan"], ["keperluan"], ["status"] ],
    tableFieldKeys:["nama_aset","pic","jabatan"],
    records:[
      { id:1, nama_aset:"Google Workspace", email:"admin@johenoffice.com", mulai:"2026-01-01", berakhir:"2027-03-15", biaya:"Rp 2.400.000/thn", pic:"IT Johen Office", jabatan:"Admin IT", keperluan:"Email & Cloud", status:"Aktif" },
      { id:2, nama_aset:"Adobe Creative Cloud", email:"tim.kreatif@johenoffice.com", mulai:"2026-01-01", berakhir:"2026-07-02", biaya:"Rp 1.600.000/thn", pic:"Tim Kreatif", jabatan:"Designer", keperluan:"Desain & Editing", status:"Aktif" },
      { id:3, nama_aset:"Microsoft 365", email:"all@johenoffice.com", mulai:"2026-01-01", berakhir:"2026-06-28", biaya:"Rp 1.800.000/thn", pic:"All Staff", jabatan:"Staff", keperluan:"Produktivitas", status:"Tidak Aktif" },
      { id:4, nama_aset:"Canva Pro", email:"marketing@johenoffice.com", mulai:"2026-01-01", berakhir:"2026-09-19", biaya:"Rp 800.000/thn", pic:"Tim Marketing", jabatan:"Marketing", keperluan:"Desain Grafis", status:"Aktif" },
      { id:5, nama_aset:"Zoom Pro", email:"ga@johenoffice.com", mulai:"2025-06-10", berakhir:"2026-06-10", biaya:"Rp 1.000.000/thn", pic:"Tim GA", jabatan:"Admin GA", keperluan:"Meeting Online", status:"Tidak Aktif" },
    ],
  },
  "aset-simcard": {
    advanced:true,
    stats:[
      {label:"Total SIM Card", value:5, icon:"smartphone", color:"accent"},
      {label:"Nomor Aktif", value:3, icon:"check-circle", color:"success"},
      {label:"Nomor Tidak Aktif", value:2, icon:"x-circle", color:"danger"},
    ],
    panelTitle:"Data SIM Card", panelSub:"Seluruh nomor SIM Card operasional perusahaan.",
    addLabel:"+ Tambah SIM Card",
    searchPlaceholder:"Cari berdasarkan nomor atau PIC",
    searchFields:["nomor","pic"],
    tableColumns:["No SIM Card","PIC","Keperluan","Status","Aksi"],
    formFields:[
      {key:"nomor", label:"Nomor SIM Card", type:"text", placeholder:"Masukan nomor SIM Card", required:true},
      {key:"pic", label:"PIC", type:"text", placeholder:"Masukan nama PIC", required:true},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Masukan jabatan", required:true},
      {key:"masa_aktif", label:"Masa Aktif", type:"date", required:true},
      {key:"masa_tenggang", label:"Masa Tenggang", type:"date", required:true},
      {key:"status_paket", label:"Status Paket Kuota", type:"select", options:["Aktif","Habis","Segera Habis"], required:true},
      {key:"status", label:"Status Kartu", type:"select", options:["Aktif","Tidak Aktif"], required:true},
      {key:"keperluan", label:"Keperluan", type:"text", placeholder:"Masukan keperluan", required:true},
    ],
    formLayout:[ ["nomor"], ["pic","jabatan"], ["masa_aktif","masa_tenggang"], ["status_paket","status"], ["keperluan"] ],
    tableFieldKeys:["nomor","pic","keperluan"],
    records:[
      { id:1, nomor:"0812-3456-7890", pic:"Dimas Pratama", jabatan:"IT Staff", masa_aktif:"2026-06-01", masa_tenggang:"2026-07-15", status_paket:"Aktif", status:"Aktif", keperluan:"Internet Harian" },
      { id:2, nomor:"0856-1122-3344", pic:"Sari Wulandari", jabatan:"Marketing Lead", masa_aktif:"2026-06-01", masa_tenggang:"2026-07-10", status_paket:"Segera Habis", status:"Aktif", keperluan:"Data & Telepon" },
      { id:3, nomor:"0878-9988-7766", pic:"Pool Kantor", jabatan:"-", masa_aktif:"2026-05-01", masa_tenggang:"2026-06-30", status_paket:"Habis", status:"Tidak Aktif", keperluan:"Cadangan" },
      { id:4, nomor:"0813-5566-7788", pic:"Andi Saputra", jabatan:"Finance Staff", masa_aktif:"2026-06-15", masa_tenggang:"2026-08-01", status_paket:"Aktif", status:"Aktif", keperluan:"Komunikasi" },
      { id:5, nomor:"0822-1212-3434", pic:"-", jabatan:"-", masa_aktif:"2026-04-01", masa_tenggang:"2026-05-15", status_paket:"Habis", status:"Tidak Aktif", keperluan:"Nomor Lama" },
    ],
  },
  "aset-kantor": {
    advanced:true,
    stats:[
      {label:"Total Peralatan", value:5, icon:"package", color:"accent"},
      {label:"Kondisi Baik", value:3, icon:"check", color:"success"},
      {label:"Perlu Servis", value:1, icon:"wrench", color:"warning"},
      {label:"Rusak", value:1, icon:"x", color:"danger"},
    ],
    panelTitle:"Peralatan Kantor", panelSub:"Inventaris peralatan kantor milik perusahaan.",
    addLabel:"+ Tambah Peralatan",
    searchPlaceholder:"Cari berdasarkan nama barang",
    searchFields:["nama_barang","pic"],
    tableColumns:["Nama Barang","Jumlah","Ruangan","Nilai","PIC","Sub Kategori","Aksi"],
    tableFieldKeys:["nama_barang","jumlah","ruangan","nilai","pic","sub_kategori"],
    formFields:[
      {key:"nama_barang", label:"Nama Barang", type:"text", placeholder:"Masukan nama barang", required:true, step:1},
      {key:"jumlah", label:"Jumlah", type:"text", placeholder:"Masukan jumlah unit", required:true, step:1},
      {key:"detail", label:"Detail", type:"text", placeholder:"Masukan detail barang", required:true, step:1},
      {key:"sub_kategori", label:"Sub Kategori", type:"select", options:["Peralatan Kantor","Alat Tulis","Bangunan",""], required:true, step:1},
      {key:"keterangan", label:"Keterangan", type:"text", placeholder:"Masukan keterangan", required:true, step:1},
      {key:"lokasi_unit", label:"Lokasi Unit", type:"text", placeholder:"Masukan lokasi unit", required:true, step:2},
      {key:"ruangan", label:"Ruangan", type:"text", placeholder:"Masukan ruangan", required:true, step:2},
      {key:"milik", label:"Milik", type:"select", options:["Milik Perusahaan","Sewa","Pinjaman"], required:true, step:2},
      {key:"pengadaan", label:"Pengadaan (Tahun)", type:"text", placeholder:"Masukan tahun pengadaan", required:true, step:3},
      {key:"tanggal_pembelian", label:"Tanggal Pembelian", type:"date", required:true, step:3},
      {key:"kategori_nilai", label:"Kategori Nilai", type:"select", options:["Rendah","Menengah","Tinggi"], required:true, step:3},
      {key:"kategori_ukuran", label:"Kategori Ukuran", type:"select", options:["Kecil","Sedang","Besar"], required:true, step:3},
      {key:"nilai", label:"Nilai", type:"text", placeholder:"Masukan nilai aset", required:true, step:3},
      {key:"waktu_pakai_per_hari", label:"Waktu Pakai Per Hari", type:"text", placeholder:"Contoh: 8 jam", required:true, step:4},
      {key:"estimasi_waktu_barang", label:"Estimasi Waktu Barang", type:"text", placeholder:"Contoh: 5 tahun", required:true, step:4},
      {key:"pengurangan_harga_per_hari", label:"Pengurangan Harga Per Hari", type:"text", placeholder:"Masukan nominal", required:true, step:4},
      {key:"harga_per_hari_ini", label:"Harga Per Hari Ini", type:"text", placeholder:"Masukan nominal", required:true, step:4},
      {key:"pic", label:"PIC", type:"text", placeholder:"Masukan nama PIC", required:true, step:5},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Masukan jabatan", required:true, step:5},
      {key:"atasan", label:"Atasan", type:"text", placeholder:"Masukan nama atasan", required:true, step:5},
      {key:"jabatan_atasan", label:"Jabatan Atasan", type:"text", placeholder:"Masukan jabatan atasan", required:true, step:5},
    ],
    formSteps:[
      {title:"Informasi Umum", desc:"Data dasar barang", icon:"package", fields:["nama_barang","jumlah","detail","sub_kategori","keterangan"]},
      {title:"Lokasi & Kepemilikan", desc:"Lokasi dan status kepemilikan", icon:"map-pin", fields:["lokasi_unit","ruangan","milik"]},
      {title:"Pengadaan & Nilai Aset", desc:"Data pengadaan dan nilai", icon:"credit-card", fields:["pengadaan","tanggal_pembelian","kategori_nilai","kategori_ukuran","nilai"]},
      {title:"Penyusutan Umur Aset", desc:"Perhitungan penyusutan", icon:"trending-down", fields:["waktu_pakai_per_hari","estimasi_waktu_barang","pengurangan_harga_per_hari","harga_per_hari_ini"]},
      {title:"Penanggung Jawab", desc:"Data penanggung jawab", icon:"user-check", fields:["pic","jabatan","atasan","jabatan_atasan"]},
    ],
    records:[
      { id:1, nama_barang:"AC Split 1 PK", jumlah:4, detail:"AC Samsung 1 PK Inverter", sub_kategori:"Peralatan Kantor", keterangan:"Digunakan di ruang kerja", lokasi_unit:"Johen Office Lt 2", ruangan:"Ruang Kerja Utama", milik:"Milik Perusahaan", pengadaan:2023, tanggal_pembelian:"2023-03-15", kategori_nilai:"Menengah", kategori_ukuran:"Sedang", nilai:"Rp 16.000.000", waktu_pakai_per_hari:"8 jam", estimasi_waktu_barang:"5 tahun", pengurangan_harga_per_hari:"Rp 8.767", harga_per_hari_ini:"Rp 4.500", pic:"Dimas Pratama", jabatan:"IT Staff", atasan:"Mega Sari", jabatan_atasan:"CEO", status:"Tersedia" },
      { id:2, nama_barang:"Proyektor Epson", jumlah:1, detail:"Epson EB-X06", sub_kategori:"Peralatan Kantor", keterangan:"Meeting room utama", lokasi_unit:"Johen Office Lt 2", ruangan:"Meeting Room Utama", milik:"Milik Perusahaan", pengadaan:2024, tanggal_pembelian:"2024-01-10", kategori_nilai:"Menengah", kategori_ukuran:"Kecil", nilai:"Rp 8.500.000", waktu_pakai_per_hari:"2 jam", estimasi_waktu_barang:"4 tahun", pengurangan_harga_per_hari:"Rp 5.822", harga_per_hari_ini:"Rp 5.200", pic:"Sari Wulandari", jabatan:"Marketing Lead", atasan:"Mega Sari", jabatan_atasan:"CEO", status:"Tersedia" },
      { id:3, nama_barang:"Printer Epson L3110", jumlah:2, detail:"Printer Infus", sub_kategori:"Peralatan Kantor", keterangan:"Front office", lokasi_unit:"Johen Office Lt 1", ruangan:"Front Office", milik:"Milik Perusahaan", pengadaan:2022, tanggal_pembelian:"2022-06-20", kategori_nilai:"Rendah", kategori_ukuran:"Kecil", nilai:"Rp 4.200.000", waktu_pakai_per_hari:"4 jam", estimasi_waktu_barang:"3 tahun", pengurangan_harga_per_hari:"Rp 3.835", harga_per_hari_ini:"Rp 1.200", pic:"Andi Saputra", jabatan:"Finance Staff", atasan:"Mega Sari", jabatan_atasan:"CEO", status:"Maintenance" },
      { id:4, nama_barang:"Kursi Kantor Ergonomis", jumlah:18, detail:"Kursi Ergonomis Mesh", sub_kategori:"Peralatan Kantor", keterangan:"Semua meja kerja", lokasi_unit:"Johen Office Lt 2", ruangan:"Ruang Kerja", milik:"Milik Perusahaan", pengadaan:2024, tanggal_pembelian:"2024-08-01", kategori_nilai:"Menengah", kategori_ukuran:"Besar", nilai:"Rp 27.000.000", waktu_pakai_per_hari:"9 jam", estimasi_waktu_barang:"5 tahun", pengurangan_harga_per_hari:"Rp 14.795", harga_per_hari_ini:"Rp 6.800", pic:"Dimas Pratama", jabatan:"IT Staff", atasan:"Mega Sari", jabatan_atasan:"CEO", status:"Tersedia" },
      { id:5, nama_barang:"Dispenser Air", jumlah:1, detail:"Dispenser Atas Bawah", sub_kategori:"Peralatan Kantor", keterangan:"Pantry", lokasi_unit:"Johen Office Lt 2", ruangan:"Pantry", milik:"Milik Perusahaan", pengadaan:2020, tanggal_pembelian:"2020-02-10", kategori_nilai:"Rendah", kategori_ukuran:"Kecil", nilai:"Rp 1.200.000", waktu_pakai_per_hari:"24 jam", estimasi_waktu_barang:"3 tahun", pengurangan_harga_per_hari:"Rp 1.096", harga_per_hari_ini:"Rp 0", pic:"-", jabatan:"-", atasan:"Mega Sari", jabatan_atasan:"CEO", status:"Rusak" },
    ],
  },

  "aset-ruko": {
    advanced:true,
    stats:[
      {label:"Total Aset Ruko", value:3, icon:"building-2", color:"accent"},
      {label:"Kondisi Baik", value:2, icon:"check-circle", color:"success"},
      {label:"Perlu Servis", value:1, icon:"wrench", color:"warning"},
    ],
    panelTitle:"Data Aset Ruko", panelSub:"Seluruh aset ruko milik perusahaan.",
    addLabel:"+ Tambah Aset",
    searchPlaceholder:"Cari berdasarkan nama aset",
    searchFields:["nama_aset","lokasi"],
    tableColumns:["Nama Aset","Lokasi","Jumlah","Kondisi","Aksi"],
    formFields:[
      {key:"nama_aset", label:"Nama Aset", type:"text", placeholder:"Masukan nama aset", required:true},
      {key:"lokasi", label:"Lokasi", type:"text", placeholder:"Masukan lokasi", required:true},
      {key:"jumlah", label:"Jumlah", type:"text", placeholder:"Masukan jumlah unit", required:true},
      {key:"kondisi", label:"Kondisi", type:"select", options:["Baik","Perlu Servis","Rusak"], required:true},
    ],
    formLayout:[ ["nama_aset","lokasi"], ["jumlah","kondisi"] ],
    tableFieldKeys:["nama_aset","lokasi","jumlah"],
    records:[
      { id:1, nama_aset:"AC Split 2 PK", lokasi:"Ruko Lt 2 - Ruang Kerja", jumlah:3, kondisi:"Baik", status:"Baik" },
      { id:2, nama_aset:"Papan Reklame", lokasi:"Depan Ruko", jumlah:1, kondisi:"Baik", status:"Baik" },
      { id:3, nama_aset:"Pintu Roller", lokasi:"Depan Ruko", jumlah:2, kondisi:"Perlu Servis", status:"Perlu Servis" },
    ],
  },

  "bayar-listrik": {
    advanced:true,
    stats:[
      {label:"Tagihan Bulan Ini", value:"Rp 7.2jt", icon:"zap", color:"accent"},
      {label:"Sudah Dibayar", value:5, icon:"check", color:"success"},
      {label:"Jatuh Tempo", value:1, icon:"clock", color:"warning"},
      {label:"Terlambat", value:0, icon:"x", color:"danger"},
    ],
    panelTitle:"Pembayaran Listrik", panelSub:"Riwayat tagihan listrik pasca bayar — tagihan terbit tiap tgl 3, jatuh tempo tgl 25.",
    addLabel:"+ Tambah Tagihan",
    searchPlaceholder:"Cari berdasarkan periode",
    searchFields:["periode"],
    tableColumns:["Periode","Tgl Tagihan","Jatuh Tempo","Nominal","Status","Tgl Bayar","Aksi"],
    formFields:[
      {key:"periode", label:"Periode", type:"text", placeholder:"Contoh: Juni 2026", required:true},
      {key:"tgl_tagihan", label:"Tanggal Tagihan", type:"date", required:true},
      {key:"jatuh_tempo", label:"Jatuh Tempo", type:"date", required:true},
      {key:"nominal", label:"Nominal", type:"text", placeholder:"Masukan nominal tagihan", required:true},
      {key:"status", label:"Status", type:"select", options:["Lunas","Jatuh Tempo","Terlambat"], required:true},
      {key:"tgl_bayar", label:"Tanggal Bayar", type:"date"},
    ],
    formLayout:[ ["periode","nominal"], ["tgl_tagihan","jatuh_tempo"], ["status","tgl_bayar"] ],
    tableFieldKeys:["periode","tgl_tagihan","jatuh_tempo","nominal"],
    tableFieldFormatters:{
      tgl_tagihan: v => v && v.includes("-") ? formatDateID(v) : v,
      jatuh_tempo: v => v && v.includes("-") ? formatDateID(v) : v,
    },
    records:[
      { id:1, periode:"Januari 2026", tgl_tagihan:"2026-01-03", jatuh_tempo:"2026-01-25", nominal:"Rp 6.800.000", status:"Lunas", tgl_bayar:"2026-01-22" },
      { id:2, periode:"Februari 2026", tgl_tagihan:"2026-02-03", jatuh_tempo:"2026-02-25", nominal:"Rp 5.200.000", status:"Lunas", tgl_bayar:"2026-02-24" },
      { id:3, periode:"Maret 2026", tgl_tagihan:"2026-03-03", jatuh_tempo:"2026-03-25", nominal:"Rp 7.800.000", status:"Lunas", tgl_bayar:"2026-03-20" },
      { id:4, periode:"April 2026", tgl_tagihan:"2026-04-03", jatuh_tempo:"2026-04-25", nominal:"Rp 6.100.000", status:"Lunas", tgl_bayar:"2026-04-19" },
      { id:5, periode:"Mei 2026", tgl_tagihan:"2026-05-03", jatuh_tempo:"2026-05-25", nominal:"Rp 9.400.000", status:"Lunas", tgl_bayar:"2026-05-23" },
      { id:6, periode:"Juni 2026", tgl_tagihan:"2026-06-03", jatuh_tempo:"2026-06-25", nominal:"Rp 7.200.000", status:"Jatuh Tempo", tgl_bayar:"" },
    ],
  },
  "bayar-internet": {
    advanced:true,
    stats:[
      {label:"Total WiFi", value:5, icon:"wifi", color:"accent"},
      {label:"Aktif", value:3, icon:"check", color:"success"},
      {label:"Jatuh Tempo", value:1, icon:"clock", color:"warning"},
      {label:"Terlambat", value:1, icon:"x", color:"danger"},
    ],
    panelTitle:"Pembayaran Internet", panelSub:"Data WiFi prabayar — Indosat billing tgl 5, IndiHome billing tgl 20. Input setelah bayar.",
    addLabel:"+ Tambah Tagihan",
    searchPlaceholder:"Cari berdasarkan nama WiFi atau PIC",
    searchFields:["nama","pic","provider"],
    tableColumns:["Nama Internet","Provider","PIC","Jabatan","Masa Tenggang","Biaya","Status","Aksi"],
    tableFieldKeys:["nama","provider","pic","jabatan","masa_tenggang","biaya"],
    tableFieldFormatters:{
      masa_tenggang: v => v && v.includes("-") ? formatDateID(v) : v,
    },
    formFields:[
      {key:"nama", label:"Nama Internet", type:"text", placeholder:"Contoh: Wifi 1 (Kantor Utama)", required:true},
      {key:"provider", label:"Provider", type:"select", options:["Indosat","IndiHome"], required:true},
      {key:"pic", label:"PIC", type:"text", placeholder:"Nama penanggung jawab", required:true},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Jabatan PIC", required:true},
      {key:"masa_tenggang", label:"Masa Tenggang", type:"date", required:true},
      {key:"biaya", label:"Biaya", type:"text", placeholder:"Contoh: Rp 300.000", required:true},
      {key:"status", label:"Status", type:"select", options:["Lunas","Jatuh Tempo","Terlambat"], required:true},
      {key:"tgl_bayar", label:"Tanggal Bayar", type:"date"},
    ],
    formLayout:[ ["nama","provider"], ["pic","jabatan"], ["masa_tenggang","biaya"], ["status","tgl_bayar"] ],
    records:[
      { id:1, nama:"Wifi 1 (Kantor Utama)", provider:"Indosat", pic:"Dimas Pratama", jabatan:"IT Staff", masa_tenggang:"2026-07-05", biaya:"Rp 300.000", status:"Lunas", tgl_bayar:"2026-06-05" },
      { id:2, nama:"Wifi 2 (R. Meeting)", provider:"Indosat", pic:"Dimas Pratama", jabatan:"IT Staff", masa_tenggang:"2026-07-05", biaya:"Rp 300.000", status:"Lunas", tgl_bayar:"2026-06-05" },
      { id:3, nama:"Wifi 3 (Lt 2)", provider:"IndiHome", pic:"Sari Wulandari", jabatan:"Marketing Lead", masa_tenggang:"2026-07-20", biaya:"Rp 500.000", status:"Lunas", tgl_bayar:"2026-06-20" },
      { id:4, nama:"Wifi 4 (Lt 1)", provider:"IndiHome", pic:"Andi Saputra", jabatan:"Finance Staff", masa_tenggang:"2026-06-18", biaya:"Rp 500.000", status:"Terlambat", tgl_bayar:"2026-05-20" },
      { id:5, nama:"Wifi 5 (Gudang)", provider:"Indosat", pic:"Dimas Pratama", jabatan:"IT Staff", masa_tenggang:"2026-07-03", biaya:"Rp 300.000", status:"Jatuh Tempo", tgl_bayar:"2026-06-05" },
    ],
  },
  "bayar-aset-digital": {
    advanced:true,
    stats:[
      {label:"Total Langganan", value:5, icon:"credit-card", color:"accent"},
      {label:"Aktif", value:3, icon:"check", color:"success"},
      {label:"Jatuh Tempo", value:1, icon:"clock", color:"warning"},
      {label:"Terlambat", value:1, icon:"x", color:"danger"},
    ],
    panelTitle:"Pembayaran Aset Digital", panelSub:"Tagihan langganan lisensi & layanan digital — input setelah bayar.",
    addLabel:"+ Tambah Tagihan",
    searchPlaceholder:"Cari berdasarkan nama aset atau PIC",
    searchFields:["nama_asset","pic","email"],
    tableColumns:["Nama Asset","Username/Email","PIC","Jabatan","Status","Aksi"],
    tableFieldKeys:["nama_asset","email","pic","jabatan"],
    formFields:[
      {key:"nama_asset", label:"Nama Asset", type:"text", placeholder:"Contoh: Outlook", required:true},
      {key:"email", label:"Email", type:"text", placeholder:"Email login", required:true},
      {key:"pic", label:"PIC", type:"text", placeholder:"Nama penanggung jawab", required:true},
      {key:"jabatan", label:"Jabatan", type:"text", placeholder:"Jabatan PIC", required:true},
      {key:"masa_aktif", label:"Masa Aktif", type:"date", required:true},
      {key:"masa_tenggang", label:"Masa Tenggang", type:"date", required:true},
      {key:"biaya", label:"Biaya", type:"text", placeholder:"Contoh: Rp 500.000", required:true},
      {key:"status", label:"Status", type:"select", options:["Lunas","Jatuh Tempo","Terlambat"], required:true},
      {key:"keperluan", label:"Keperluan", type:"text", placeholder:"Contoh: Desain Grafis"},
    ],
    formLayout:[ ["nama_asset","email"], ["pic","jabatan"], ["masa_aktif","masa_tenggang"], ["biaya","status"], ["keperluan"] ],
    records:[
      { id:1, nama_asset:"Outlook", email:"outlook@johenoffice.com", pic:"Dimas Pratama", jabatan:"IT Staff", masa_aktif:"2026-06-01", masa_tenggang:"2026-07-01", biaya:"Rp 1.200.000", status:"Lunas", keperluan:"Email Bisnis" },
      { id:2, nama_asset:"Canva", email:"canva@johenoffice.com", pic:"Sari Wulandari", jabatan:"Marketing Lead", masa_aktif:"2026-06-10", masa_tenggang:"2026-07-10", biaya:"Rp 800.000", status:"Lunas", keperluan:"Desain Grafis" },
      { id:3, nama_asset:"iLoveIMG", email:"iloveimg@johenoffice.com", pic:"Andi Saputra", jabatan:"Finance Staff", masa_aktif:"2026-06-15", masa_tenggang:"2026-07-15", biaya:"Rp 300.000", status:"Lunas", keperluan:"Edit File" },
      { id:4, nama_asset:"ChatGPT", email:"chatgpt@johenoffice.com", pic:"Dimas Pratama", jabatan:"IT Staff", masa_aktif:"2026-05-20", masa_tenggang:"2026-06-19", biaya:"Rp 500.000", status:"Terlambat", keperluan:"AI Tools" },
      { id:5, nama_asset:"CapCut Pro", email:"capcut@johenoffice.com", pic:"Sari Wulandari", jabatan:"Marketing Lead", masa_aktif:"2026-06-01", masa_tenggang:"2026-06-28", biaya:"Rp 600.000", status:"Jatuh Tempo", keperluan:"Video Editing" },
    ],
  },
  "bayar-ipl": {
    advanced:true,
    stats:[
      {label:"Biaya IPL / Bulan", value:"Rp 1.700.000", icon:"building-2", color:"accent"},
      {label:"Pengingat", value:"Tgl 20", icon:"bell", color:"warning"},
      {label:"Jatuh Tempo", value:"Tgl 22", icon:"clock", color:"danger"},
    ],
    panelTitle:"Pembayaran IPL Ruko", panelSub:"Iuran pengelolaan lingkungan — Summarecon Bandung.",
    addLabel:"+ Tambah Tagihan",
    searchPlaceholder:"Cari berdasarkan periode",
    searchFields:["periode"],
    tableColumns:["Periode","Tanggal Bayar","Tagihan Bulan Ini","Jatuh Tempo","Status","Aksi"],
    tableFieldKeys:["periode","tgl_bayar","tagihan","jatuh_tempo"],
    tableFieldFormatters:{
      tgl_bayar: v => v && v.includes("-") ? formatDateID(v) : (v || "-"),
      jatuh_tempo: v => v && v.includes("-") ? formatDateID(v) : v,
    },
    formFields:[
      {key:"periode", label:"Periode", type:"text", placeholder:"Contoh: Juli 2026", required:true},
      {key:"tagihan", label:"Tagihan", type:"text", default:"Rp 1.700.000", placeholder:"Rp 1.700.000", required:true},
      {key:"jatuh_tempo", label:"Jatuh Tempo", type:"date", required:true},
      {key:"tgl_bayar", label:"Tanggal Bayar", type:"date"},
      {key:"status", label:"Status", type:"select", options:["Lunas","Jatuh Tempo","Terlambat"], required:true},
    ],
    formLayout:[ ["periode"], ["tagihan"], ["jatuh_tempo","tgl_bayar"], ["status"] ],
    records:[
      { id:1, periode:"Juni 2026", tagihan:"Rp 1.700.000", jatuh_tempo:"2026-06-22", tgl_bayar:"", status:"Jatuh Tempo" },
      { id:2, periode:"Mei 2026", tagihan:"Rp 1.700.000", jatuh_tempo:"2026-05-22", tgl_bayar:"2026-05-21", status:"Lunas" },
      { id:3, periode:"April 2026", tagihan:"Rp 1.700.000", jatuh_tempo:"2026-04-22", tgl_bayar:"2026-04-20", status:"Lunas" },
      { id:4, periode:"Maret 2026", tagihan:"Rp 1.700.000", jatuh_tempo:"2026-03-22", tgl_bayar:"2026-03-20", status:"Lunas" },
    ],
  },

  "kelola-tim": {
    panelTitle:"Kelola Tim", panelSub:"Kelola pembagian tim perusahaan.",
    addLabel:"+ Tambah Tim",
    searchPlaceholder:"Cari berdasarkan nama tim",
    searchFields:["nama_tim","kepala_tim"],
    tableColumns:["Nama Tim","Deskripsi","Anggota","Kepala Tim","Status","Aksi"],
    tableFieldKeys:["nama_tim","deskripsi","anggota","kepala_tim"],
    formFields:[
      {key:"nama_tim", label:"Nama Tim", type:"text", placeholder:"Contoh: IT", required:true},
      {key:"deskripsi", label:"Deskripsi", type:"text", placeholder:"Contoh: Divisi Teknologi Informasi", required:true},
      {key:"anggota", label:"Anggota", type:"text", placeholder:"Contoh: 5 orang", required:true},
      {key:"kepala_tim", label:"Kepala Tim", type:"text", placeholder:"Contoh: Dimas Pratama", required:true},
      {key:"status", label:"Status", type:"select", options:["Aktif","Nonaktif"], required:true},
    ],
    formLayout:[ ["nama_tim","kepala_tim"], ["deskripsi"], ["anggota","status"] ],
    records:[
      { id:1, nama_tim:"IT", deskripsi:"Divisi Teknologi Informasi", anggota:"5 orang", kepala_tim:"Dimas Pratama", status:"Aktif" },
      { id:2, nama_tim:"Marketing", deskripsi:"Divisi Pemasaran", anggota:"4 orang", kepala_tim:"Sari Wulandari", status:"Aktif" },
      { id:3, nama_tim:"Finance", deskripsi:"Divisi Keuangan", anggota:"3 orang", kepala_tim:"Andi Saputra", status:"Aktif" },
      { id:4, nama_tim:"HR", deskripsi:"Divisi Sumber Daya Manusia", anggota:"3 orang", kepala_tim:"Rina Marlina", status:"Nonaktif" },
    ],
  },
  "kelola-aset-meeting": {
    panelTitle:"Kelola Aset Meeting", panelSub:"Inventaris perlengkapan pendukung meeting.",
    addLabel:"+ Tambah Aset",
    searchPlaceholder:"Cari berdasarkan nama aset",
    searchFields:["nama_aset","deskripsi"],
    tableColumns:["Nama Asset","Deskripsi","Jumlah","Status","Aksi"],
    tableFieldKeys:["nama_aset","deskripsi","jumlah"],
    formFields:[
      {key:"nama_aset", label:"Nama Asset", type:"text", placeholder:"Contoh: Proyektor Epson", required:true},
      {key:"deskripsi", label:"Deskripsi", type:"text", placeholder:"Contoh: Proyektor Epson EB-X06", required:true},
      {key:"jumlah", label:"Jumlah", type:"text", placeholder:"Contoh: 2 unit", required:true},
      {key:"status", label:"Status", type:"select", options:["Tersedia","Dipinjam","Rusak"], required:true},
    ],
    formLayout:[ ["nama_aset","jumlah"], ["deskripsi"], ["status"] ],
    records:[
      { id:1, nama_aset:"Proyektor Epson EB-X06", deskripsi:"Proyektor Epson EB-X06", jumlah:"2 unit", status:"Tersedia" },
      { id:2, nama_aset:"Microphone Wireless", deskripsi:"Microphone Wireless", jumlah:"4 unit", status:"Dipinjam" },
      { id:3, nama_aset:"Whiteboard Mobile", deskripsi:"Whiteboard Mobile 120x180cm", jumlah:"1 unit", status:"Tersedia" },
      { id:4, nama_aset:"Speaker Bluetooth", deskripsi:"Speaker Bluetooth JBL", jumlah:"2 unit", status:"Rusak" },
      { id:5, nama_aset:"TV 55 Inch", deskripsi:"TV LED 55 Inch untuk presentasi", jumlah:"1 unit", status:"Tersedia" },
      { id:6, nama_aset:"Kursi Tambahan", deskripsi:"Kursi lipat tambahan meeting", jumlah:"10 unit", status:"Dipinjam" },
    ],
  },
  "kelola-ruangan": {
    advanced:true,
    panelTitle:"Kelola Ruangan", panelSub:"Kelola data ruangan meeting.",
    addLabel:"+ Tambah Ruangan",
    formFields:[
      {key:"nama_ruangan", label:"Nama Ruangan", type:"text", placeholder:"Contoh: Meeting Room Utama", required:true},
      {key:"kapasitas", label:"Kapasitas", type:"text", placeholder:"Contoh: 50 orang", required:true},
      {key:"lantai", label:"Lantai", type:"text", placeholder:"Contoh: Lantai 1", required:true},
      {key:"fasilitas", label:"Fasilitas", type:"text", placeholder:"Pisahkan dengan koma, contoh: Proyektor, TV", required:true},
      {key:"status", label:"Status", type:"select", options:["Aktif","Tidak Aktif"], required:true},
    ],
    formLayout:[ ["nama_ruangan","kapasitas"], ["lantai"], ["fasilitas"], ["status"] ],
    records:[
      { id:1, nama_ruangan:"Meeting Room Utama", kapasitas:"50 orang", lantai:"Lantai 1", fasilitas:"Proyektor, TV, Speaker, Whiteboard, AC, Kursi, Meja", status:"Aktif" },
      { id:2, nama_ruangan:"Ruang Serbaguna", kapasitas:"5 orang", lantai:"Lantai 3", fasilitas:"Kursi, Sofa, Meja Kecil", status:"Aktif" },
    ],
  },
  "kelola-akun": {
    advanced:true,
    panelTitle:"Kelola Akun Koordinator", panelSub:"Kelola akun koordinator divisi dengan akses TERBATAS (menu Meeting saja).",
    addLabel:"+ Tambah Koordinator",
    searchPlaceholder:"Cari berdasarkan nama, email, atau divisi",
    tableColumns:["Nama","Email","Divisi","Status","Aksi"],
    formFields:[
      {key:"nama", label:"Nama Lengkap", type:"text", placeholder:"Masukan nama", required:true},
      {key:"email", label:"Email", type:"text", placeholder:"Masukan email", required:true},
      {key:"divisi", label:"Divisi", type:"select", options:["Creative","PUBG","MLBB","Free Fire","Valorant","Roblox","eFootball","Transaksi","IT"], required:true},
    ],
    formLayout:[ ["nama","email"], ["divisi"] ],
    records:[
      { id:101, nama:"Budi Hartono", email:"budi@johenoffice.com", divisi:"Creative", status:"Aktif" },
      { id:102, nama:"Citra Dewi", email:"citra@johenoffice.com", divisi:"PUBG", status:"Aktif" },
      { id:103, nama:"Eko Prasetyo", email:"eko@johenoffice.com", divisi:"MLBB", status:"Aktif" },
      { id:104, nama:"Fitri Handayani", email:"fitri@johenoffice.com", divisi:"Free Fire", status:"Aktif" },
      { id:105, nama:"Gilang Ramadhan", email:"gilang@johenoffice.com", divisi:"Valorant", status:"Aktif" },
      { id:106, nama:"Hesti Purnama", email:"hesti@johenoffice.com", divisi:"Roblox", status:"Aktif" },
      { id:107, nama:"Irfan Hakim", email:"irfan@johenoffice.com", divisi:"eFootball", status:"Aktif" },
      { id:108, nama:"Joko Susilo", email:"joko@johenoffice.com", divisi:"Transaksi", status:"Aktif" },
      { id:109, nama:"Ketut Wirawan", email:"ketut@johenoffice.com", divisi:"IT", status:"Aktif" },
    ],
  },
  "kelola-admin": {
    advanced:true,
    panelTitle:"Kelola Admin", panelSub:"Kelola admin dengan akses PENUH ke seluruh menu sistem.",
    addLabel:"+ Tambah Admin",
    searchPlaceholder:"Cari berdasarkan nama atau email",
    tableColumns:["Nama","Email","Role","Status","Aksi"],
    formFields:[
      {key:"nama", label:"Nama Lengkap", type:"text", placeholder:"Masukan nama", required:true},
      {key:"email", label:"Email", type:"text", placeholder:"Masukan email", required:true},
      {key:"role", label:"Role Akses", type:"select", options:["super_admin","ceo","general_manager","head_of_store","hr","admin_ga"], required:true},
    ],
    formLayout:[ ["nama","email"], ["role"] ],
    records:[
      { id:1, nama:"Admin GA", email:"admin.ga@johenoffice.com", role:"super_admin", status:"Aktif" },
      { id:2, nama:"Dimas Pratama", email:"dimas@johenoffice.com", role:"admin_ga", status:"Aktif" },
      { id:3, nama:"Sari Wulandari", email:"sari@johenoffice.com", role:"hr", status:"Aktif" },
      { id:4, nama:"Andi Saputra", email:"andi@johenoffice.com", role:"general_manager", status:"Aktif" },
      { id:5, nama:"Linda Kusuma", email:"linda@johenoffice.com", role:"head_of_store", status:"Nonaktif" },
      { id:6, nama:"Mega Sari", email:"mega@johenoffice.com", role:"ceo", status:"Aktif" },
    ],
  },
};

// ===================== DASHBOARD UTAMA =====================
const DASHBOARD_SUMMARY = {
  meeting: {
    id:"meeting", icon:"users", color:"accent",
    title:"Dashboard Meeting", subtitle:"Ringkasan aktivitas meeting seluruh tim",
    goTo:"meeting-saya",
    stats:[
      {label:"Total Meeting", value:5, icon:"layout-grid"},
      {label:"Menunggu Approval", value:1, icon:"clock"},
      {label:"MOM Belum Diisi", value:3, icon:"file-warning"},
      {label:"Selesai Bulan Ini", value:2, icon:"check-check"},
    ],
    tableTitle:"Meeting Terbaru", columns:["Judul Meeting","Tanggal","Status"],
    rows:[
      {cols:["Meeting Tim IT","18 Jun 2026"], status:"Selesai"},
      {cols:["Sinkronisasi Tim Produk","20 Jun 2026"], status:"Disetujui"},
      {cols:["Rapat Tim IT","13 Jun 2026"], status:"Menunggu"},
      {cols:["Review Kontrak Sewa","08 Jun 2026"], status:"Ditolak"},
    ],
  },
  aset: {
    id:"aset", icon:"box", color:"warning",
    title:"Dashboard Data Aset", subtitle:"Ringkasan seluruh aset perusahaan",
    goTo:"aset-kendaraan",
    stats:[
      {label:"Total Kendaraan", value:9, icon:"car"},
      {label:"Lisensi Digital", value:18, icon:"laptop"},
      {label:"SIM Card Aktif", value:9, icon:"smartphone"},
      {label:"Peralatan Kantor", value:32, icon:"package"},
    ],
    tableTitle:"Aset Perlu Perhatian", columns:["Nama Aset","Kategori","Status"],
    rows:[
      {cols:["Mitsubishi L300","Kendaraan"], status:"Maintenance"},
      {cols:["Zoom Pro","Aset Digital"], status:"Expired"},
      {cols:["Microsoft 365","Aset Digital"], status:"Jatuh Tempo"},
      {cols:["Dispenser Air","Peralatan Kantor"], status:"Rusak"},
    ],
  },
  pembayaran: {
    id:"pembayaran", icon:"credit-card", color:"success",
    title:"Dashboard Pembayaran", subtitle:"Ringkasan tagihan & pembayaran operasional",
    goTo:"bayar-listrik",
    stats:[
      {label:"Total Tagihan Bulan Ini", value:"Rp 13.3jt", icon:"wallet"},
      {label:"Sudah Dibayar", value:42, icon:"check"},
      {label:"Jatuh Tempo", value:5, icon:"clock"},
      {label:"Terlambat", value:1, icon:"x"},
    ],
    tableTitle:"Tagihan Jatuh Tempo", columns:["Jenis","Nominal","Status"],
    rows:[
      {cols:["Listrik","Rp 4.200.000"], status:"Jatuh Tempo"},
      {cols:["Internet","Rp 1.500.000"], status:"Jatuh Tempo"},
      {cols:["Google Workspace","Rp 2.400.000"], status:"Jatuh Tempo"},
      {cols:["Adobe Creative Cloud","Rp 1.600.000"], status:"Terlambat"},
    ],
  },
  akun: {
    id:"akun", icon:"user-cog", color:"info",
    title:"Dashboard Akun", subtitle:"Ringkasan tim, akun, dan hak akses",
    goTo:"kelola-tim",
    stats:[
      {label:"Total Anggota Tim", value:24, icon:"users"},
      {label:"Total Akun Sistem", value:24, icon:"user"},
      {label:"Total Admin", value:4, icon:"shield-check"},
      {label:"Akun Nonaktif", value:1, icon:"user-x"},
    ],
    tableTitle:"Akun Perlu Tindak Lanjut", columns:["Nama","Role","Status"],
    rows:[
      {cols:["Rina Marlina","HR Staff"], status:"Nonaktif"},
      {cols:["Andi Saputra","Akun Sistem"], status:"Menunggu"},
    ],
  },
};
